name: compilation-deployment

releases:
- name: custom-vm-release
  version: "1.0.0"

stemcells:
- alias: default
  os: ubuntu-jammy
  version: latest

instance_groups: []

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-90000
  update_watch_time: 1000-90000